import {useState} from 'react';
import {blankScope,save,useAction,useCollection} from '../api';
import {validateGeneration} from '../state_model';
import type {Item,Page,Question} from '../types';
import {Feedback,ScopePicker} from './common';
import styles from '../knowledge.module.css';
export function GenerationForm({revision,onChange}:{revision:number;onChange:()=>void}){
  const [scope,setScope]=useState(blankScope),[mode,setMode]=useState('variant'),[original,setOriginal]=useState(0),[variant,setVariant]=useState(5),[difficulty,setDifficulty]=useState('regular'),[kind,setKind]=useState('short'),[purpose,setPurpose]=useState('practice'),[references,setReferences]=useState<string[]>([]),[fill,setFill]=useState(false);
  const action=useAction(onChange);const questions=useCollection<Item<Question>>('questions?status=reviewed',revision);
  const available=questions.data?.items.filter(q=>q.data.scope.grade===scope.grade&&q.data.scope.edition===scope.edition&&q.data.scope.semester===scope.semester&&q.data.scope.knowledge_point_ids.every(p=>scope.knowledge_point_ids.includes(p)))||[];
  return <section className={styles.card}><span className={styles.badge}>03 · AI 变式与组题</span><h2>相同知识点，不同解题情境</h2><p className={styles.hint}>题库决定参考题型，教材限定出题范围。AI 新题进入待核对区，审核后才能加入题组。</p>
    <form className={styles.form} onSubmit={e=>{e.preventDefault();void action.run(async()=>{const payload={scope,difficulty,response_type:kind,purpose,original_count:original,variant_count:variant,reference_version_ids:references,allow_ai_fill:fill};const errors=validateGeneration(payload).errors;if(errors.length)throw Error(errors.join('；'));if(!scope.chapter_version_ids.length)throw Error('请先选择已审核教材章节');await save('generations',{...payload,request_id:crypto.randomUUID()});},'已提交出题任务，请在处理任务区查看进度；新题将在题库中等待核对');}}>
      <ScopePicker value={scope} revision={revision} onChange={s=>{setScope(s);setReferences([]);}}/>
      <div className={styles.row}><label>组题方式<select value={mode} onChange={e=>{setMode(e.target.value);setOriginal(e.target.value==='variant'?0:2);setVariant(e.target.value==='original'?0:3);}}><option value="original">原题</option><option value="variant">AI 变式</option><option value="mixed">原题 + 变式</option></select></label><label>用途<select value={purpose} onChange={e=>setPurpose(e.target.value)}><option value="practice">练习</option><option value="test">测试</option></select></label><label>难度<select value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option value="regular">常规</option><option value="advanced">进阶</option><option value="challenge">挑战</option></select></label></div>
      <div className={styles.row}>{mode!=='variant'&&<label>原题数量<input type="number" min={1} max={50} required value={original} onChange={e=>setOriginal(Number(e.target.value))}/></label>}{mode!=='original'&&<><label>变式数量<input type="number" min={1} max={50} required value={variant} onChange={e=>setVariant(Number(e.target.value))}/></label><label>新题题型<select value={kind} onChange={e=>setKind(e.target.value)}><option value="single">单选题</option><option value="multiple">多选题</option><option value="boolean">判断题</option><option value="short">填空 / 简答</option><option value="worked">解答题</option></select></label></>}</div>
      <fieldset><legend>选择原题 / 参考题（当前范围内 {available.length} 道）</legend>{available.map(q=><label className={styles.check} key={q.id}><input type="checkbox" checked={references.includes(q.data.current_version_id!)} onChange={()=>setReferences(references.includes(q.data.current_version_id!)?references.filter(id=>id!==q.data.current_version_id):[...references,q.data.current_version_id!])}/>{q.data.prompt.slice(0,110)}</label>)}{!available.length&&<p className={styles.hint}>还没有符合此范围的已审核题。可先审核题目，或明确允许从教材生成候选题。</p>}</fieldset><Feedback error={questions.error}/>
      {mode!=='original'&&<><label className={styles.check}><input type="checkbox" checked={fill} onChange={e=>setFill(e.target.checked)}/>没有参考题时，允许 AI 根据已审核教材生成候选题</label><p className={styles.notice}>只发送所选参考题和教材片段，使用你的教师 AI 服务。图形题如缺少可靠新图，会要求人工补图，不沿用尺寸不一致的原图。</p></>}
      <button className={styles.primary} disabled={action.busy}>{action.busy?'提交中…':'开始组题'}</button><Feedback {...action}/>
    </form></section>;
}
